"""
draft_post.py
Generates a blog post draft from pipeline output.

Usage:
    python scripts/draft_post.py <sha256>
"""

import sys
import json
import argparse
from pathlib import Path
from datetime import date

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

REPORTS_DIR = REPO_ROOT / "output" / "reports"
DOCS_DIR = REPO_ROOT / "docs" / "_posts"


def draft_post(sha256: str) -> None:
    # Find synthesis
    syn_path = REPORTS_DIR / f"{sha256}.synthesis.json"
    if not syn_path.exists():
        # Try prefix match
        matches = list(REPORTS_DIR.glob(f"{sha256}*.synthesis.json"))
        if not matches:
            print(f"  [!] No synthesis found for {sha256[:16]}...")
            return
        syn_path = matches[0]

    with open(syn_path, "r", encoding="utf-8") as f:
        raw = json.load(f)

    sample = raw.get("sample", {})
    syn = raw.get("synthesis", raw)
    tech = syn.get("technical_report", {})
    ttp = syn.get("ttp_mapping", {})
    yara = syn.get("yara_rule", {})
    sigma = syn.get("sigma_rule", {})

    family = (sample.get("malware_family") or "unknown").title()
    sha_short = sha256[:16]
    today = date.today().isoformat()

    # Extract TTP IDs for tags
    technique_ids = [t.get("id", "") for t in ttp.get("techniques", []) if t.get("id")]

    # Check for delta report
    delta_path = REPORTS_DIR / f"{sha256}.delta.json"
    delta_section = ""
    if delta_path.exists():
        with open(delta_path, "r", encoding="utf-8") as f:
            delta = json.load(f)
        comparisons = delta.get("comparisons", [])
        if comparisons:
            top = comparisons[0]
            delta_section = f"""## Corpus Comparison

Compared against {delta.get('corpus_size', 0)} previously analyzed samples.

**Top match:** {(top.get('compared_family') or 'unknown').title()} (`{top['compared_sha256'][:16]}...`) — overlap score {top['overlap_score']}

"""
            shared_ttps = top.get("shared_attack_ttps", [])
            if shared_ttps:
                delta_section += f"Shared TTPs: {', '.join(shared_ttps)}\n\n"
            shared_caps = top.get("shared_capabilities", [])
            if shared_caps:
                delta_section += f"Shared capabilities: {', '.join(shared_caps[:10])}\n\n"

    # Build the post
    post = f"""---
title: "Analysis: {family} ({sha_short}...)"
date: {today}
tags: [{family.lower()}, {', '.join(technique_ids[:5])}]
---

## Why This Sample

<!-- YOUR VOICE: 2-3 sentences. Where did you find it? What caught your eye? -->


## Executive Summary

{tech.get('executive_summary', '[no executive summary generated]')}

## Technical Analysis

{tech.get('technical_summary', '[no technical summary generated]')}

## MITRE ATT&CK Mapping

{ttp.get('narrative', '[no TTP narrative generated]')}

**Confidence:** {ttp.get('confidence', 'unknown')} — {ttp.get('reasoning', '')}

| Technique | Tactic | Evidence |
|-----------|--------|----------|
"""

    for t in ttp.get("techniques", []):
        post += f"| {t.get('id','')} {t.get('name','')} | {t.get('tactic','')} | {t.get('evidence','')} |\n"

    post += f"""
## Detection Rules

### YARA

**Confidence:** {yara.get('confidence', 'unknown')} — {yara.get('reasoning', '')}

```yara
{yara.get('rule', '[no rule generated]')}
```

### Sigma

**Confidence:** {sigma.get('confidence', 'unknown')} — {sigma.get('reasoning', '')}

**CrowdStrike:** {sigma.get('crowdstrike_notes', '')}

**Splunk:** {sigma.get('splunk_notes', '')}

```yaml
{sigma.get('rule', '[no rule generated]')}
```

{delta_section}## Key Indicators

"""

    for indicator in tech.get("key_indicators", []):
        post += f"- `{indicator}`\n"

    post += f"""
## Recommended Actions

"""

    for action in tech.get("recommended_actions", []):
        post += f"- {action}\n"

    post += f"""
## Takeaway

<!-- YOUR VOICE: 1-2 sentences. What should a defender do with this? -->

---

*Generated by [Mal-Intel-Pipeline](https://github.com/Winkz0/Mal-Intel-Pipeline) — analysis SHA256: `{sha256}`*
"""

    # Save
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"{today}-{family.lower().replace(' ', '-')}-{sha_short}.md"
    out_path = DOCS_DIR / filename
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(post)

    print(f"\n{'='*60}")
    print(f"  Blog Draft Generated")
    print(f"{'='*60}")
    print(f"  File   : {out_path}")
    print(f"  Family : {family}")
    print(f"  SHA256 : {sha256[:32]}...")
    print(f"")
    print(f"  Fill in the two <!-- YOUR VOICE --> sections and push.")
    print(f"{'='*60}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate blog post draft from pipeline output")
    parser.add_argument("sha256", help="SHA256 of the analyzed sample")
    args = parser.parse_args()
    draft_post(args.sha256)