"""
validate.py
M9 Rule Validation Orchestrator.
Validates YARA and Sigma rules generated by M8 for a given sample.
This is human checkpoint #3 — analyst reviews validation results
before rules are considered production-ready.

Usage:
    python validate.py <sha256>
    python validate.py --all
"""

import sys
import json
import logging
import argparse
from pathlib import Path
from datetime import datetime, timezone

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from pipeline.rule_validation.validate_yara import validate_yara_rule
from pipeline.rule_validation.validate_sigma import validate_sigma_rule

logger = logging.getLogger(__name__)

YARA_DIR = REPO_ROOT / "output" / "rules" / "yara"
SIGMA_DIR = REPO_ROOT / "output" / "rules" / "sigma"
VALIDATION_DIR = REPO_ROOT / "output" / "logs" / "validation"


def run_validation(sha256: str) -> dict:
    report = {
        "sha256": sha256,
        "validated_at": datetime.now(timezone.utc).isoformat(),
        "yara": None,
        "sigma": None,
        "overall_valid": False,
        "ready_for_production": False,
        "analyst_approved": False,
    }

    print(f"\n{'='*60}")
    print(f"  CHECKPOINT #3 — RULE VALIDATION")
    print(f"  Sample: {sha256[:32]}...")
    print(f"{'='*60}")

    # YARA validation
    yara_matches = list(YARA_DIR.glob(f"{sha256}*.yar"))
    if yara_matches:
        yara_path = yara_matches[0]
        print(f"\n  [1/2] Validating YARA rule: {yara_path.name}")
        yara_result = validate_yara_rule(yara_path)
        report["yara"] = yara_result
        status = "✓ VALID" if yara_result["valid"] else f"✗ INVALID — {yara_result['error']}"
        print(f"        {status}")
    else:
        print(f"\n  [1/2] YARA rule not found for {sha256[:16]}... — skipping")
        report["yara"] = {"valid": False, "error": "Rule file not found", "skipped": True}

    # Sigma validation
    sigma_matches = list(SIGMA_DIR.glob(f"{sha256}*.yml"))
    if sigma_matches:
        sigma_path = sigma_matches[0]
        print(f"  [2/2] Validating Sigma rule: {sigma_path.name}")
        sigma_result = validate_sigma_rule(sigma_path)
        report["sigma"] = sigma_result
        status = "✓ VALID" if sigma_result["valid"] else f"✗ INVALID — {sigma_result['error']}"
        print(f"        {status}")
    else:
        print(f"  [2/2] Sigma rule not found for {sha256[:16]}... — skipping")
        report["sigma"] = {"valid": False, "error": "Rule file not found", "skipped": True}

    # Overall assessment
    yara_valid = report["yara"].get("valid", False)
    sigma_valid = report["sigma"].get("valid", False)
    report["overall_valid"] = yara_valid and sigma_valid

    print(f"\n{'─'*60}")
    print(f"  YARA  : {'✓ valid' if yara_valid else '✗ invalid'}")
    print(f"  Sigma : {'✓ valid' if sigma_valid else '✗ invalid'}")
    print(f"  Overall: {'✓ PASS' if report['overall_valid'] else '✗ FAIL'}")
    print(f"{'─'*60}")

    # Checkpoint #3 — analyst approval
    print(f"\n  Review the rules above and approve for production use.")
    print(f"  [y] Approve — mark rules as production-ready")
    print(f"  [n] Reject — rules need revision")
    print(f"  [s] Skip approval — save validation results only")

    while True:
        cmd = input("\n  Decision: ").strip().lower()
        if cmd == "y":
            report["analyst_approved"] = True
            report["ready_for_production"] = report["overall_valid"]
            print(f"  [+] Rules approved for production.")
            break
        elif cmd == "n":
            report["analyst_approved"] = False
            report["ready_for_production"] = False
            print(f"  [-] Rules rejected — revision required.")
            break
        elif cmd == "s":
            print(f"  [~] Skipping approval — results saved.")
            break
        else:
            print(f"  [!] Enter y, n, or s.")

    # Save validation report
    save_validation_report(report)
    return report


def save_validation_report(report: dict) -> Path:
    VALIDATION_DIR.mkdir(parents=True, exist_ok=True)
    sha256 = report["sha256"]
    out_path = VALIDATION_DIR / f"{sha256}.validation.json"
    with open(out_path, "w") as f:
        json.dump(report, f, indent=2)
    print(f"\n  Validation report saved: {out_path.name}")
    return out_path


def get_all_rule_hashes() -> list[str]:
    yara_hashes = {p.stem for p in YARA_DIR.glob("*.yar")}
    sigma_hashes = {p.stem for p in SIGMA_DIR.glob("*.yml")}
    return list(yara_hashes | sigma_hashes)


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.WARNING,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    )

    parser = argparse.ArgumentParser(description="M9 Rule Validation Orchestrator")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("sha256", nargs="?", help="SHA256 (or prefix) of sample to validate")
    group.add_argument("--all", action="store_true", help="Validate all generated rules")
    args = parser.parse_args()

    if args.all:
        hashes = get_all_rule_hashes()
        print(f"Found {len(hashes)} rule set(s) to validate")
        for h in hashes:
            run_validation(h)
    else:
        run_validation(args.sha256)